- name: lesson 2. Task 1
  user: ansible
  become: yes
  become_method: sudo
  become_user: root
  hosts: nodes
  vars_files:
    - secret.yaml
  tasks:
  - name: Add users
    user: name="{{ item }}" append=yes password="{{ password | password_hash('sha512') }}" update_password=on_create comment={{ item }}@example.com create_home=yes
    loop:
      - Alice
      - Bob
      - Carol